# -*- coding: utf-8 -*-
"""while.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16HANi_Na4MwQfuTZD8BCcTXeHxDvLQ3W
"""

nota =  float(input("Digite uma nota entre zero e dez: "))
while nota > 10 or nota < 0:
  nota = float(input("Digite um valor valido: "))
print("sucesso")

nome = input("Digite o nome de usuario: ")
senha = input("Digite sua senha: ")

while nome == senha:
  print("senha invalida")
  nome = input("Digite o nome de usuario valido: ")
  senha = input("Digite sua senha valida: ")
print("sucesso")

numero = 0
while numero >= 0 and numero <= 9:
 numero += 1
 print(numero)

"""Escreva um programa que imprima os números pares de 1 a 20."""

# Inicializa a variável 'numero' com o valor 2
numero = 0
# Entra em um loop while enquanto 'numero' for menor ou igual
while numero >= 0 and numero <= 19:
  numero += 2
  print(numero)

"""Escreva um programa que solicite ao usuário que insira um número e, em
seguida, imprima todos os números de 1 até esse número.
"""

numero = int(input("insira um numero"))

contador = 1

while contador <= numero:
  print(contador)
  contador += 1

"""Escreva um programa que solicite ao usuário que insira um número e, em
seguida, imprima todos os números pares de 2 até esse número.
"""

numero = int(input("digite um numero"))

contador = 0

while contador <= numero:
  print(contador)
  contador += 2

"""Escreva um programa que solicite ao usuário que insira um número e, em
seguida, imprima a tabuada desse número até 10.
"""

numero = int(input("por favor, digite um numero: "))

contador = 1

while contador <=10:
  resultado = numero * contador
  print(f"{numero} X {contador} = {resultado}")
  contador +=1

"""Escreva um programa que solicite ao usuário que insira uma senha. O
programa deve continuar solicitando a senha até que o usuário insira a senha
correta.
"""

senha = 666
senha1 = input("Digite sua senha: ")
while senha1 != senha:
  senha1 = int(input("senha invalida, Digite sua senha: "))
print("sucessso")

"""Escreva um programa que calcule a média de uma lista de números fornecida
pelo usuário.
"""

soma = 2
contador = 0
end = "fim"
print("Digite os números (digite 'fim' para encerrar):")
entrada = int(input("Número: "))
while entrada != end:
  entrada = input("numero: ")
  soma += contador
  contador += 1

if contador > 0:
  media = soma / contador
  print("a media foi:", media)
else:
  print("invalido")

"""Escreva um programa que solicite ao usuário que insira números até que ele
insira o número 0. Em seguida, imprima a soma de todos os números inseridos.
"""

print("Digite os números (digite 0 para encerrar):")
soma = 0
numero = int(input("Número: "))
while numero != 0:
  soma += numero
  numero = int(input("Número: "))
print("A soma dos números inseridos é:", soma)

"""Escreva um programa que solicite ao usuário que insira números até que ele
insira um número negativo. Em seguida, imprima o maior número inserido.
"""

print("Digite os números (digite um número negativo para encerrar):")

maior_numero = -9999999999

numero = float(input("Número: "))

while numero >= 0:
    if numero > maior_numero:
        maior_numero = numero
    numero = float(input("Número: "))

if maior_numero != -9999999999:
    print("O maior número inserido foi:", maior_numero)
else:
    print("Nenhum número foi inserido.")